[theme]
theme = "solarized-dark"

[icons]
icons = "awesome4"

[[block]]
block = "music"
player = "spotify"
format = " $icon {$combo.str(max_w:30,rot_interval:0.2) $prev $play $next |}"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "enp6s0"
format = " $icon {$ip |}"
interval = 5

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = " $icon {$used/$total ($available free) |}"
interval = 60

[[block]]
block = "cpu"
format = " $icon {$barchart $utilization $frequency $boost |}"
interval = 5

[[block]]
block = "temperature"
format = " $icon {$min min $max max $average avg |}"
interval = 10
inputs = ["CPUTIN"]

[[block]]
block = "memory"
format = " $icon {$mem_used/$mem_total |}"
interval = 5

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %b %d %r') "
interval = 1

