theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "music"
player = "spotify"
marquee = true
marquee_interval = 3
marquee_speed = 0.1
max_width = 30
buttons = ["prev", "play", "next"]

[[block]]
block = "sound"

[[block]]
block = "net"
device = "enp5s0"
format = "{ip} {bitrate} {speed_down;K*b} {speed_up;K*b}"
interval = 5

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
format = "{icon} {used}/{total} ({available} free)"
interval = 60

[[block]]
block = "cpu"
warning  = 75
critical = 90
format = "{barchart} {utilization} {frequency}"
interval = 5

[[block]]
block = "temperature"
collapsed = false
format = "{min} min {max} max {average} avg"
interval = 10

[[block]]
block = "memory"
display_type = "memory"
icons = true
clickable = false
warning_mem = 75
critical_mem = 90
format_mem = "{mem_used:4}/{mem_total:1}"
interval = 5

[[block]]
block = "time"
format = "%a %b %d %r"
interval = 1

