theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "enp5s0"
ssid = true
ip = true
speed_up = false
graph_up = false
speed_down = false
interval = 15

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 60

[[block]]
block = "cpu"
interval = 10
warning  = 75
critical = 90
frequency = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mum}MB/{MTm}MB"
clickable = false
interval = 10
warning_mem = 75
critical_mem = 90

[[block]]
block = "sound"

# [[block]]
# block = "music"
# player = "spotify"
# marquee = true
# marquee_interval = 10
# marquee_speed = 0.5
# buttons = ["prev", "play", "next"]

[[block]]
block = "time"
interval = 1
format = "%a %b %d %r"

