#!/usr/bin/env zsh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
dir=$dir/../
cd $dir
git ls-files --recurse-submodules | \
  ctags --tag-relative=no -L - -f"$dir/$$.tags" --languages=javascript,sql,c,c++
mv "$dir/$$.tags" "$dir/tags"
