#!/bin/bash

OG_DIR=`pwd`

if [ ! -z $2 ]; then
    for f in "${@:2}"; do
        cp "${f}" /home/dillon/.bin/pandoc_template/
    done
    cd /home/dillon/.bin/pandoc_template
    pandoc --template lassi_template.tex -o "${1}" "${@:2}"
    mv "${1}" "${OG_DIR}"/"${1}"
    for f in "${@:2}"; do
        rm "${f}"
    done
    cd "${OG_DIR}"
else
    echo "No input files"
fi

